CREATE DATABASE IF NOT EXIST BLOG;
USE BLOG;
SET SQL_SAFE_UPDATES =0;

CREATE TABLE user (
    id INT PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    email VARCHAR(40) NOT NULL,
    para VARCHAR(5000) NOT NULL,
    enroll BIGINT,
    password VARCHAR(100)
)
